export const poketypes = [
  { value: "bug", lable: "bug" },
  { value: "dark", lable: "dark" },
  { value: "dragon", lable: "dragon" },
  { value: "electric", lable: "electric" },
  { value: "fairy", lable: "fairy" },
  { value: "fighting", lable: "fighting" },
  { value: "fire", lable: "fire" },
  { value: "flying", lable: "flying" },
  { value: "ghost", lable: "ghost" },
  { value: "grass", lable: "grass" },
  { value: "ground", lable: "ground" },
  { value: "ice", lable: "ice" },
  { value: "normal", lable: "normal" },
  { value: "poison", lable: "poison" },
  { value: "psychic", lable: "psychic" },
  { value: "rock", lable: "rock" },
  { value: "steel", lable: "steel" },
  { value: "water", lable: "water" },
];
